service: todo-app

frameworkVersion: '2'

plugins:
  # - serverless-webpack
  - serverless-export-env
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local
  - serverless-offline

# package:
#   individually: true

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      migrate: true
      sharedDb: true
      convertEmptyValues: true
      noStart: true
    migration:
      dir: src/db/offline/migrations

  export-env:
    overwrite: true
    enableOffline: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-1
  profile: serverlessadmin
  environment:
    DYNAMODB_TABLE_NAME: ${self:service}-${opt:stage, self:provider.stage}
    TODO_APP_PK: ${self:service}
    DYNAMODB_ARN: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_NAME}'

functions:
  - ${file(./config/functions/graphql.yml)}

resources:
  - ${file(./config/resources/todoTable.yml)}
